version: '3.3'
services:
  web:
    image: keymetrics/pm2:latest-alpine
    ports:
      - "8080:8080"
    volumes:
      - .:/host
    working_dir: /host
    command: ["pm2-runtime", "start", "pm2.json"]
