export const eventTableName = 'mm-prod-event'
export const inviteTableName = 'mm-prod-invite'
export const rsvpTableName = 'mm-prod-rsvp'
export const suggestionTableName = 'mm-prod-suggestion'
export const userTableName = 'mm-prod-user'
export const voteTableName = 'mm-prod-vote'
export const notificationTableName = 'mm-prod-notification'
